import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/navbar'
import Footer from './components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='main-body '>
          <div>
            <Navbar />
          </div>
          <div className='fluid-container'>
            {children}
          </div>  
          <div>
            <Footer />
          </div>
        </div>
       </body>
    </html>
  );
}
